#!/bin/sh
set -e

case "$1" in
    configure)
        mkdir -p /etc/vac/vac.conf.d /etc/vac/extras_imperative.d \
                 /etc/vac/extras_informative.d /etc/vac/vac.sub \
                 /var/lib/vac/sub /var/log/vac

        if [ ! -f /etc/vac/vac-id ]; then
            uuidgen > /etc/vac/vac-id
            chmod 600 /etc/vac/vac-id
        fi
        ;;
esac

#DEBHELPER#
